[pytest]
testpaths = tests
markers =
    develop: test in develop
    ethernet: ethernet protocol
    soem: soem protocol
    soem_multislave: soem protocol with multislave
    canopen: canopen protocol
    virtual: Tests without connection
    fsoe: Safety over EtherCAT
    fsoe_phase2: Safety over EtherCAT phase 2 tests
    biss_c_flaky: Marks tests that are flaky for BISS-C configuration
    valid_versions_for_product: Specify valid firmware version range for a specific product (part_number, min=version, max=version, interfaces=[list of interfaces], xfail=reason)
    not_valid_version_for_product: Specify invalid firmware version range for a specific product (part_number, min=version, max=version, interfaces=[list of interfaces], xfail=reason)
    not_valid_for_product: Specify part number for which the test should never run (part_number, interfaces=[list of interfaces], xfail=reason)
log_cli = False
log_cli_level = INFO
env=
    D:TESTS_OUTPUT_DIR=tests/outputs
    D:RESOURCES_DIR=resources
    D:WIRESHARK_DIR=wireshark
    D:WIRESHARK_INSTALLATION_PATH=C:\\Program Files\\Wireshark
    D:START_WIRESHARK_TIMEOUT_S=10.0
